const fruitsInfo = [
  {
    name: "Cherries",
    evolutionIndex: 0,
    fruitCode: "CH",
    sprite: "cherry.png",
    radius: 33 / 2,
  },
  {
    name: "Strawberries",
    evolutionIndex: 1,
    fruitCode: "ST",
    sprite: "strawberry.png",
    radius: 48 / 2,
  },
  {
    name: "Grapes",
    evolutionIndex: 2,
    fruitCode: "GR",
    sprite: "grape.png",
    radius: 61 / 2,
  },
  {
    name: "Dekopons",
    evolutionIndex: 3,
    fruitCode: "DK",
    sprite: "dekopon.png",
    radius: 69 / 2,
  },
  {
    name: "Persimmon",
    evolutionIndex: 4,
    fruitCode: "PS",
    sprite: "persimmon.png",
    radius: 89 / 2,
  },
  {
    name: "Apple",
    evolutionIndex: 5,
    fruitCode: "AP",
    sprite: "apple.png",
    radius: 114 / 2,
  },
  {
    name: "Pear",
    evolutionIndex: 6,
    fruitCode: "PR",
    sprite: "pear.png",
    radius: 129 / 2,
  },
  {
    name: "Peach",
    evolutionIndex: 7,
    fruitCode: "PE",
    sprite: "peach.png",
    radius: 156 / 2,
  },
  {
    name: "Pineapple",
    evolutionIndex: 8,
    fruitCode: "PN",
    sprite: "pineapple.png",
    radius: 177 / 2,
  },
  {
    name: "Melon",
    evolutionIndex: 9,
    fruitCode: "ML",
    sprite: "melon.png",
    radius: 220 / 2,
  },
  {
    name: "Watermelon",
    evolutionIndex: 10,
    fruitCode: "WM",
    sprite: "watermelon.png",
    radius: 259 / 2,
  },
]

export default fruitsInfo;