const fruitsInfo = [
  {
    name: "Cherries",
    evolutionIndex: 0,
    fruitCode: "CH",
    sprite: "sprites/cherry.png",
    radius: 33 / 2,
  },
  {
    name: "Strawberries",
    evolutionIndex: 1,
    fruitCode: "ST",
    sprite: "sprites/strawberry.png",
    radius: 48 / 2,
  },
  {
    name: "Grapes",
    evolutionIndex: 2,
    fruitCode: "GR",
    sprite: "sprites/grape.png",
    radius: 61 / 2,
  },
  {
    name: "Dekopons",
    evolutionIndex: 3,
    fruitCode: "DK",
    sprite: "sprites/dekopon.png",
    radius: 69 / 2,
  },
  {
    name: "Persimmon",
    evolutionIndex: 4,
    fruitCode: "PS",
    sprite: "sprites/persimmon.png",
    radius: 89 / 2,
  },
  {
    name: "Apple",
    evolutionIndex: 5,
    fruitCode: "AP",
    sprite: "sprites/apple.png",
    radius: 114 / 2,
  },
  {
    name: "Pear",
    evolutionIndex: 6,
    fruitCode: "PR",
    sprite: "sprites/pear.png",
    radius: 129 / 2,
  },
  {
    name: "Peach",
    evolutionIndex: 7,
    fruitCode: "PE",
    sprite: "sprites/peach.png",
    radius: 156 / 2,
  },
  {
    name: "Pineapple",
    evolutionIndex: 8,
    fruitCode: "PN",
    sprite: "sprites/pineapple.png",
    radius: 177 / 2,
  },
  {
    name: "Melon",
    evolutionIndex: 9,
    fruitCode: "ML",
    sprite: "sprites/melon.png",
    radius: 220 / 2,
  },
  {
    name: "Watermelon",
    evolutionIndex: 10,
    fruitCode: "WM",
    sprite: "sprites/watermelon.png",
    radius: 259 / 2,
  },
]

export default fruitsInfo;